### ISSUE TITLE
Nuke 14.0 compatibility?

### ISSUE THREAD

**Issue by RyanJForth** [masterkeech/PRefToMotion#10]
Hey, a coworker tried to build this for Nuke 14 but was getting errors. Looks like this hasn't been updated for about 3 years which would explain that. Are there any plans to update this for Nuke 14? It's a great plugin would love to keep using it!

**Comment by masterkeech** [comment]
Should be compatible for Nuke 14, I'm compiling in on Linux Centos 7.8 for all flavours of Nuke with no change to the code. I did make a slight bug fix about 3 months ago so sounds like you missed that? which means this project has been updated recently ;)

**Comment by RyanJForth** [comment]
Oh, that's great to know!  I did see your change 3 months ago which is what gave me hope but it was just for 1 file so I thought maybe it might have just been a quick bug fix. Sorry, I'm a Python Programmer (my C++ is very rusty, on my "to do" list...) and the developer who helped me build from the source initially is on vacation. Someone else tried but couldn't get it working. I guess we'll have to revisit it and fix the issue on our end. Thank you for confirming! Any tips for building? We're on Linux Centos 7.9 currently.

**Comment by RyanJForth** [comment]
We got it working. The wrong version of C++ was being used to compile was the issue.
